---
title: "Setup"
output: html_notebook
---

```{r setup}
knitr::opts_knit$set(root.dir="~/projects/HMP2_Share")
knitr::opts_chunk$set(root.dir = "~/projects/HMP2_Share")
library(reticulate)
reticulate::use_virtualenv('../.venv/', required = T)
```


# Install R packages
```{r}
.main_packages <- c('data.table','tidyverse','janitor', 'ggsci','ggthemes','ggfortify','ggraph','pheatmap',
                   'arsenal','splitstackshape','htmltab','phyloseq','vegan', 'dabestr', 'caret',
                   'scales', 'edgeR','metagenomeSeq', 'DESeq2','lpsymphony','Maaslin2',
                   'Rtsne', 'EnhancedVolcano', 'biomaRt', 'GOstats','pathfindR', 'esetVis', 'sva', 'ashr',
                   'reticulate', 'MultiAssayExperiment','UpSetR','compositions', 'dbplyr', 'lmerTest')
.github_packages<-c('bioFAM/MOFA','zdk123/SpiecEasi', 'mathelab/IntLIM','bioFAM/MOFAdata',
                    'hong-revo/glmnetUtils','bioFAM/MOFA2/MOFA2' )

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(.main_packages[!.main_packages %in% installed.packages()], update = TRUE, ask = FALSE)
devtools::install_github(.github_packages[!.github_packages %in% installed.packages()])
```

# Install Python packages
Note: you NEED a previously existing python >3 installation. The cell will call for pip3 for compatibility

```{bash}
#~/miniconda3/bin/virtualenv .venv
source .venv/bin/activate
pip install numpy matplotlib 
pip install pandas scikit-learn scipy dabest xgboost merf gmem shap scikits.bootstrap category_encoders scikit-bio mofapy2 pyarrow seaborn dill 
```

#GSK HG only
```{r}
#make sure you have the SSH keys set up in the TFS (from ~/.ssh/id_rsa.pub)
library(tidyverse)

db_c <- 
('key,value
database,gene_gwas_use\n
tmp_write_db,gene_gwas_shared')
write_lines(db_c, '~/.gtx_config.csv')


library(devtools)
library(glue)
library(purrr)

# Workaround function to install from GSK TFS using ssh: url
install_tfs <- function(url, branch = 'master', dependencies = FALSE, upgrade = FALSE) {
  if (missing(url)) {
    stop('url argument is required')
  } 
  reMatch <- regexpr('([^/]+)$', url)
  if (reMatch > 0) {
    package <- substr(url, reMatch, reMatch + attr(reMatch, 'match.length'))
  } else {
    stop(glue('Could not determine package name from url [ {url} ]'))
  }
  message(glue('Determined package name \'{package}\' from url'))
  tmpdir <- tempdir() # per-session tmpdir, *not* unique
  message(glue('$ rm -rf {tmpdir}/{package}'))
  system(glue('rm -rf {tmpdir}/{package}'))
  message(glue('$ cd {tmpdir} && git clone --branch {branch} {url}'))
  system(glue('cd {tmpdir} && git clone --branch {branch} {url}'))
  commit <- sub('^commit ', '', system(glue('cd {tmpdir}/{package} && git log -n 1'), intern = TRUE)[1])
  message(glue('Appending RemoteSha: {commit} to {tmpdir}/{package}/DESCRIPTION'))
  write.table(glue('RemoteSha: {commit}\n'), 
              quote = FALSE, row.names = FALSE, col.names = FALSE,
              file = glue('{tmpdir}/{package}/DESCRIPTION'), append = TRUE)
  message('Installing...')
  devtools::install(glue('{tmpdir}/{package}'),
                    dependencies = dependencies, 
                    upgrade = upgrade)
  message(glue('$ rm -rf {tmpdir}/{package}'))
  system(glue('rm -rf {tmpdir}/{package}'))
}

# Create function to safely install
safe_install <- purrr::safely(install_tfs)

# Execute the safe_install
exec <- safe_install(url          = "ssh://tfs.gsk.com:22/tfs/Target_Sciences/Target%20Sciences/_git/gtx", 
                     branch       = "master", 
                     dependencies = TRUE,
                     upgrade      = TRUE)
```

